# Generated by Django 5.1.15 on 2026-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('speed_limit_kmh', models.IntegerField(blank=True, null=True)),
                ('min_speed_limit_kmh', models.IntegerField(blank=True, null=True)),
                ('max_speed_limit_kmh', models.IntegerField(blank=True, null=True)),
                ('warning_radius_meters', models.IntegerField(default=700)),
                ('camera_type', models.CharField(default='monitored_zone', max_length=50)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('source', models.CharField(default='initial_image_dataset', max_length=100)),
                ('last_updated', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['road_name', 'location_name'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
