# Generated by Django 5.1.15 on 2026-06-29 19:12

import police_presence.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicePresenceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_required_after', models.DateTimeField(default=police_presence.models._fifteen_minutes_from_now)),
                ('expires_at', models.DateTimeField(default=police_presence.models._thirty_minutes_from_now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_confirmation', 'Needs Confirmation'), ('confirmed_present', 'Confirmed Present'), ('not_present', 'Not Present'), ('expired', 'Expired')], default='active', max_length=30)),
                ('present_confirmations', models.IntegerField(default=0)),
                ('not_present_confirmations', models.IntegerField(default=0)),
                ('source', models.CharField(default='anonymous_community_report', max_length=100)),
                ('reported_by_device_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
