# Generated by Django 5.1.15 on 2026-07-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policepresencealert',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PolicePresenceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64)),
                ('present', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='police_presence.policepresencealert')),
            ],
            options={
                'unique_together': {('alert', 'device_hash')},
            },
        ),
    ]
