# Generated by Django 5.1.15 on 2026-07-10 23:19

import police_presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_presence', '0002_policepresencealert_last_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policepresencealert',
            name='expires_at',
            field=models.DateTimeField(default=police_presence.models._fifty_minutes_from_now),
        ),
    ]
